version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
