# Generated by Django 5.2 on 2025-04-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(null=True, upload_to='news_images/')),
                ('conteudo', models.TextField()),
                ('data_de_publicacao', models.DateField()),
                ('autor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('categoria', models.CharField(choices=[('poder', 'Poder'), ('tributos', 'Tributos'), ('saude', 'Saúde'), ('energia', 'Energia'), ('trabalhista', 'Trabalhista')], default='poder', max_length=15)),
                ('acesso', models.CharField(choices=[('public', 'Público'), ('pro', 'Restrito a PRO')], default='public', max_length=10)),
            ],
        ),
    ]
