# Generated by Django 5.2 on 2025-04-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_news_autor_alter_news_imagem_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='role',
            field=models.CharField(
                choices=[('Admin', 'Admin'),
                         ('Editor', 'Editor'),
                         ('Leitor', 'Leitor')],
                default='Leitor', max_length=10),
        ),
    ]
