# Generated by Django 5.2 on 2025-04-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_consolidated_migration'),
    ]

    operations = [
        # As colunas já existem no banco de dados, ignorando a criação.
    ]
