# Generated by Django 5.2 on 2025-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
                ('conteudo', models.CharField(max_length=1000)),
                ('data_de_publicacao', models.DateField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
