# Generated by Django 5.2 on 2025-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='acesso',
            field=models.CharField(choices=[('public', 'Público'), ('pro', 'Restrito a PRO')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='categoria',
            field=models.CharField(choices=[('poder', 'Poder'), ('tributos', 'Tributos'), ('saude', 'Saúde'), ('energia', 'Energia'), ('trabalhista', 'Trabalhista')], default='poder', max_length=15),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='data_de_publicacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='imagem',
            field=models.ImageField(upload_to='news_images/'),
        ),
    ]
